language: node_js
node_js:
  - '7'
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
addons:
  chrome: stable # have Travis install chrome stable.
env:
  global:
    - ENCRYPTION_LABEL: "d7ffc1eaa225"
    - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
    - TRIGGER_REPO_SLUG: "patternfly-webcomponents/patternfly-webcomponents"
    - TRIGGER_REPO_BRANCH: "master"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install git+https://github.com/patternfly/patternfly-eng-release.git
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: true

script:
  - sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -w

after_success:
  - npm run publish-travis
